"""
Machine learning decision engine — aligned with model.ipynb (colleague's notebook).

- RandomForestClassifier: direction = return_1d > 0  ->  BUY / SELL
- RandomForestRegressor: predicts close price (optional context in signals)
- Data: data/all_stocks.csv (generated by DataLoader.py)

Train: python decision_engine.py
Used by tools.get_trading_signal via predict_signal().
"""

import os
from typing import Optional

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    mean_squared_error,
    r2_score,
)

from Config import (
    CONFIDENCE_THRESHOLD,
    DATA_FOLDER,
    MAX_TREE_DEPTH,
    RANDOM_STATE,
    STOCKS,
)

# Notebook feature set (no return_1d in X — label uses return_1d)
FEATURE_COLUMNS = [
    "open",
    "high",
    "low",
    "volume",
    "return_5d",
    "ma_20",
    "ma_50",
    "rsi_14",
    "macd",
    "macd_signal",
    "macd_hist",
    "bb_upper",
    "bb_mid",
    "bb_lower",
    "volatility_20",
]

# Binary classifier: 0 = down, 1 = up
CLASS_TO_SIGNAL = {0: "SELL", 1: "BUY"}

MODEL_DIR = "models"
MODEL_PATH = os.path.join(MODEL_DIR, "decision_model.pkl")
ALL_STOCKS_CSV = "all_stocks.csv"

N_ESTIMATORS = 100


def _load_all_stocks(data_folder: str = DATA_FOLDER) -> pd.DataFrame:
    """Load combined CSV (notebook: data/all_stocks.csv)."""
    path = os.path.join(data_folder, ALL_STOCKS_CSV)
    if os.path.exists(path):
        df = pd.read_csv(path)
        if "Date" in df.columns:
            df["Date"] = pd.to_datetime(df["Date"])
            df = df.sort_values(by=["Date", "ticker"]).reset_index(drop=True)
        return df

    # Fallback: merge per-ticker CSVs
    frames = []
    for ticker in STOCKS:
        p = os.path.join(data_folder, f"{ticker}.csv")
        if not os.path.exists(p):
            continue
        part = pd.read_csv(p, index_col=0, parse_dates=True)
        part = part.reset_index().rename(columns={"index": "Date", "date": "Date"})
        if "Date" not in part.columns and part.columns[0] != "Date":
            part = part.rename(columns={part.columns[0]: "Date"})
        part["ticker"] = ticker
        frames.append(part)
    if not frames:
        raise FileNotFoundError(
            f"No {ALL_STOCKS_CSV} in {data_folder}. Run: python DataLoader.py"
        )
    return pd.concat(frames, ignore_index=True).sort_values(
        by=["Date", "ticker"]
    ).reset_index(drop=True)


def prepare_dataset(data_folder: str = DATA_FOLDER) -> tuple[pd.DataFrame, pd.Series, pd.Series]:
    """
    Build X, y_clf (direction), y_reg (close) — same logic as model.ipynb.
    """
    data = _load_all_stocks(data_folder)
    df = data.copy()

    if "Date" in df.columns:
        df["Date"] = pd.to_datetime(df["Date"])

    df = df.sort_values(by=["Date", "ticker"]).reset_index(drop=True)
    df["direction"] = (df["return_1d"] > 0).astype(int)

    cols_needed = FEATURE_COLUMNS + ["close", "direction"]
    df = df[cols_needed + (["ticker"] if "ticker" in df.columns else [])].dropna()
    df = df.reset_index(drop=True)

    X = df[FEATURE_COLUMNS]
    y_clf = df["direction"]
    y_reg = df["close"]
    return X, y_clf, y_reg


def _create_classifier() -> RandomForestClassifier:
    return RandomForestClassifier(
        n_estimators=N_ESTIMATORS,
        max_depth=MAX_TREE_DEPTH,
        random_state=RANDOM_STATE,
        class_weight="balanced",
        n_jobs=-1,
    )


def _create_regressor() -> RandomForestRegressor:
    return RandomForestRegressor(
        n_estimators=N_ESTIMATORS,
        max_depth=MAX_TREE_DEPTH,
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )


def train_model(
    data_folder: str = DATA_FOLDER,
    save_path: str = MODEL_PATH,
) -> dict:
    """Train classifier + regressor (model.ipynb) with chronological split."""
    X, y_clf, y_reg = prepare_dataset(data_folder)
    n = len(X)
    train_end = int(n * 0.70)
    val_end = int(n * 0.85)

    splits = {
        "train": slice(0, train_end),
        "val": slice(train_end, val_end),
        "test": slice(val_end, n),
    }

    clf = _create_classifier()
    reg = _create_regressor()

    clf.fit(X.iloc[splits["train"]], y_clf.iloc[splits["train"]])
    reg.fit(X.iloc[splits["train"]], y_reg.iloc[splits["train"]])

    def _clf_acc(sl, name):
        pred = clf.predict(X.iloc[sl])
        acc = accuracy_score(y_clf.iloc[sl], pred)
        print(f"{name} accuracy: {acc:.3f}")
        return acc

    def _reg_metrics(sl, name):
        pred = reg.predict(X.iloc[sl])
        y_true = y_reg.iloc[sl]
        rmse = float(np.sqrt(mean_squared_error(y_true, pred)))
        r2 = float(r2_score(y_true, pred))
        print(f"{name} regression — RMSE: {rmse:.2f}, R2: {r2:.4f}")
        return rmse, r2

    print("\n--- Classifier (direction: return_1d > 0) ---")
    train_acc = _clf_acc(splits["train"], "Train")
    val_acc = _clf_acc(splits["val"], "Validation")
    test_acc = _clf_acc(splits["test"], "Test")
    print("\nTest classification report:")
    print(
        classification_report(
            y_clf.iloc[splits["test"]],
            clf.predict(X.iloc[splits["test"]]),
            target_names=["DOWN (SELL)", "UP (BUY)"],
            zero_division=0,
        )
    )

    print("\n--- Regressor (close price) ---")
    _reg_metrics(splits["train"], "Train")
    _reg_metrics(splits["val"], "Validation")
    test_rmse, test_r2 = _reg_metrics(splits["test"], "Test")

    os.makedirs(os.path.dirname(save_path) or ".", exist_ok=True)
    bundle = {
        "classifier": clf,
        "regressor": reg,
        "feature_columns": FEATURE_COLUMNS,
        "class_to_signal": CLASS_TO_SIGNAL,
        "confidence_threshold": CONFIDENCE_THRESHOLD,
        "source": "model.ipynb",
        "label": "direction = (return_1d > 0)",
    }
    joblib.dump(bundle, save_path)
    print(f"\n[SAVED] Models -> {save_path}")

    return {
        "train_accuracy": train_acc,
        "val_accuracy": val_acc,
        "test_accuracy": test_acc,
        "test_rmse": test_rmse,
        "test_r2": test_r2,
        "rows": n,
    }


def load_model(path: str = MODEL_PATH):
    if not os.path.exists(path):
        return None
    return joblib.load(path)


def _ensure_model(path: str = MODEL_PATH):
    bundle = load_model(path)
    if bundle is None:
        print("[ML] No saved model — training now (first run may take ~30s)...")
        train_model(path=path)
        bundle = load_model(path)
    return bundle


def _get_classifier(bundle):
    """Support old bundle format (single 'model' key) and new notebook format."""
    if "classifier" in bundle:
        return bundle["classifier"]
    if "model" in bundle:
        return bundle["model"]
    raise KeyError("Invalid model bundle — retrain with: python decision_engine.py")


def _get_regressor(bundle):
    return bundle.get("regressor")


def predict_signal(
    ticker: str,
    data_folder: str = DATA_FOLDER,
    model_path: str = MODEL_PATH,
) -> dict:
    """
    Predict BUY / SELL for latest row (binary classifier from model.ipynb).
    Low confidence -> HOLD.
    """
    ticker = ticker.strip().upper()
    path = os.path.join(data_folder, f"{ticker}.csv")
    if not os.path.exists(path):
        raise ValueError(f"No CSV for {ticker}. Run DataLoader.py first.")

    df = pd.read_csv(path, index_col=0, parse_dates=True)
    row = df.iloc[-1]
    bundle = _ensure_model(model_path)
    clf = _get_classifier(bundle)
    features = bundle.get("feature_columns", FEATURE_COLUMNS)
    class_map = bundle.get("class_to_signal", CLASS_TO_SIGNAL)

    X = pd.DataFrame([row[features].astype(float)])
    proba = clf.predict_proba(X)[0]
    classes = clf.classes_
    best_idx = int(np.argmax(proba))
    best_class = int(classes[best_idx])
    confidence = float(proba[best_idx])

    signal = class_map.get(best_class, "HOLD")
    threshold = bundle.get("confidence_threshold", CONFIDENCE_THRESHOLD)
    trusted = confidence >= threshold
    final_signal = signal if trusted else "HOLD"

    predicted_close = None
    reg = _get_regressor(bundle)
    if reg is not None:
        predicted_close = float(reg.predict(X)[0])

    return {
        "ticker": ticker,
        "signal": final_signal,
        "raw_signal": signal,
        "confidence": round(confidence, 3),
        "trusted": trusted,
        "threshold": threshold,
        "as_of": str(df.index[-1].date()),
        "close": float(row["close"]),
        "predicted_close": predicted_close,
        "rsi_14": float(row["rsi_14"]),
        "model_source": bundle.get("source", "RandomForest"),
    }


def format_prediction(result: dict) -> str:
    t = result["ticker"]
    lines = [
        f"ML signal for {t} (as of {result['as_of']}): {result['signal']}",
        (
            f"Model: RandomForestClassifier (model.ipynb) | "
            f"Confidence: {result['confidence']:.1%}"
        ),
        f"Direction vote: {result['raw_signal']} (up/down from return_1d pattern) | "
        f"Threshold: {result['threshold']:.0%}",
    ]
    if not result["trusted"]:
        lines.append(
            f"Confidence below {result['threshold']:.0%} - showing HOLD (low conviction)."
        )
    if result.get("predicted_close") is not None:
        lines.append(
            f"Regressor close estimate: USD {result['predicted_close']:.2f} "
            f"(actual: USD {result['close']:.2f})"
        )
    lines.append(f"Close: USD {result['close']:.2f} | RSI(14): {result['rsi_14']:.1f}")
    lines.append(
        "Disclaimer: ML signal for decision support only, not guaranteed returns."
    )
    return "\n".join(lines)


if __name__ == "__main__":
    metrics = train_model()
    print("\nMetrics:", metrics)
    sample = predict_signal("AAPL")
    print("\nSample prediction (AAPL):")
    print(format_prediction(sample))
